# Generated by Django 3.1.3 on 2020-11-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='sno',
        ),
        migrations.AddField(
            model_name='contest',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
