# Generated by Django 3.1.3 on 2020-12-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drona', '0002_auto_20201121_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
