# Generated by Django 3.1.3 on 2020-12-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drona', '0003_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
