# Generated by Django 3.1.3 on 2020-12-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drona', '0004_delete_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='duration',
            field=models.CharField(default='na', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='start_time',
            field=models.CharField(default='na', max_length=40),
            preserve_default=False,
        ),
    ]
