# Generated by Django 3.1.3 on 2020-11-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='handle',
        ),
    ]
