# Generated by Django 3.1.3 on 2020-12-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_customuser_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gurus',
            field=models.CharField(default='', max_length=500),
        ),
    ]
